-- Create colors table if it doesn't exist
CREATE TABLE IF NOT EXISTS colors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  color_name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable realtime for the colors table
alter publication supabase_realtime add table colors;

-- Insert initial data if the table is empty
INSERT INTO colors (color_name)
SELECT data.color_name
FROM (
  VALUES
    ('Red'),
    ('Blue'),
    ('Green'),
    ('Yellow'),
    ('Black')
) AS data(color_name)
WHERE NOT EXISTS (SELECT 1 FROM colors LIMIT 1);
