-- Create products table if it doesn't exist
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_sku VARCHAR(255) NOT NULL UNIQUE,
  product_name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  isi_dus INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable row level security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Create policy for public access
DROP POLICY IF EXISTS "Public products access"
ON products;
CREATE POLICY "Public products access"
ON products FOR ALL
USING (true);

-- Enable realtime
alter publication supabase_realtime add table products;

-- Insert initial data
INSERT INTO products (product_sku, product_name, category, isi_dus)
VALUES 
  ('SKU001', 'Running Shoes', 'Footwear', 12),
  ('SKU002', 'Sports Socks', 'Accessories', 24),
  ('SKU003', 'Training Shoes', 'Footwear', 10)
ON CONFLICT (product_sku) DO NOTHING;