-- Create inventory_pasang table if it doesn't exist
CREATE TABLE IF NOT EXISTS inventory_pasang (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT NOT NULL REFERENCES locations(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  color_id BIGINT NOT NULL REFERENCES colors(id),
  size_id BIGINT NOT NULL REFERENCES sizes(id),
  stok_pasang INTEGER NOT NULL DEFAULT 0,
  variant_sku VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS on the table
ALTER TABLE inventory_pasang ENABLE ROW LEVEL SECURITY;

-- Create policies for inventory_pasang
CREATE POLICY "Enable read access for all users" ON inventory_pasang FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON inventory_pasang FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users" ON inventory_pasang FOR UPDATE TO authenticated USING (true);

-- Enable realtime for inventory_pasang table
ALTER PUBLICATION supabase_realtime ADD TABLE inventory_pasang;
